name: "KubeRolloutTrigger"
description: "Fetch a GitHub OIDC token and POST {image, tags} to a rollout trigger endpoint"
author: "unitvectory-labs"

inputs:
  audience:
    description: "OIDC audience"
    required: true
  url:
    description: "Webhook URL to POST to"
    required: true
  image:
    description: "Image name to deploy"
    required: true
  tags:
    description: "Image tags to deploy (comma-separated, e.g., 'dev' or 'v1.0.0,v1.0,v1,latest')"
    required: true
  timeout-seconds:
    description: "HTTP timeout in seconds"
    required: false
    default: "10"

runs:
  using: "node24"
  main: "dist/index.js"
